### PR TITLE
Added OpenGLViewRenderer to WPF Backend

### PR DESCRIPTION
**Pull request by jsuarezruiz**
### Description of Change ###

Added **OpenGLViewRenderer** to WPF Backend.

### Bugs Fixed ###

- None.

### API Changes ###

Added:
 - OpenGLViewRenderer.

### Behavioral Changes ###

Used OpenTK to add OpenGL support. Open Toolkit library is a fast, low-level C# wrapper for OpenGL and OpenAL. More information: [https://github.com/opentk/opentk](https://github.com/opentk/opentk)

### PR Checklist ###

- [ ] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of master at time of PR
- [ ] Changes adhere to coding standard
- [ ] Consolidate commits as makes sense

### CODE REVIEW

**Comment by mohachouch** [comment]
Hi,

Thank for your contribution.

I have just one question : Why you have deleted the "Submodule Xamarin.Forms.Build"

I think, he can cause conflict with the Xamarin forms base projet.

Thanks

**Comment by jsuarezruiz** [comment]
It was definitely a mistake. That submodule should not be deleted.

**Comment by entdark** [comment]
Any info when to expect this on the main Xamarin.Forms release?

**Comment by mohachouch** [comment]
I can not give you a date yet. I hope as soon as possible.

To discuss bugs, idea ... 

You can use this page: https://github.com/mohachouch/forms-wpf-progress/issues

**Pull request merged**
